### ISSUE TITLE
Use known compatible rules

### ISSUE THREAD

**Issue by didroe** [Bearer/bearer#1088]
We currently always download the latest rules. If a rule change is made that requires newer functionality in the CLI (and isn't backwards compatible), we end up with the latest rule set failing to scan in older CLI versions.

We need a way to allow older CLI versions to continue running with rules they are compatible with.

**Comment by cfabianski** [comment]
I can think of 3 options:

## Option 1 (recommended)

We introduce a new information in the rule (`version`) and if we try to compile a rule that is incompatible with the binary, we raise and display the following message
> It looks like you are running a version of the binary that is incompatible with the following rule(s) (rule-1, rule-2). Update Bearer <link-to-update-instruction> to start using the version <id> of the rules

## Option 2

If the compilation of the rules fails (we let it fail) and it's not the latest version of the binary, we display the following message
> It looks like you are running an older version of the binary that might be incompatible with the latest ruleset. Try updating bearer <link-to-update-instruction>

## Option 3

We have a database of the binaries and their compatible rulesets. Instead of downloading the rules directly from GitHub, we download it from our backend and we check against that DB which version we can use.
