### ISSUE TITLE
Easily reverse engineer a fingerprint, "explain" mode

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#1132]
From a fingerprint, it would be good to easily know which file, line and rule associated does it correspond, like an "explainer" mode.

Why? When you start to have multiple fingerprints excluded, it becomes difficult to keep track of them beyond doing code comments in the bearer.yml file.

Possible proposed solution:
```bash
bearer explain fingerprint_id

File: routes/quarantineServer.ts:14
Severity: MEDIUM
Rule: External control of filename or path detected. [CWE-73]
https://docs.bearer.com/reference/rules/javascript_express_external_file_upload

```
[Update]
We may want to also add the information if the fingerprint is still up-to-date or not (cf https://github.com/Bearer/bearer/issues/1132)

**Comment by cfabianski** [comment]
That is not possible in the current state since the [fingerprint](https://github.com/Bearer/bearer/blob/6017ffadcaa05d6e8f0d87cc67f03f1895a6eab4/pkg/report/output/security/security.go#L205) is calculated using MD5 and that is not reversible (at least not without a DB).

We would need to change the way we generate the fingerprint (for instance a JWT or a Base64 encode) would allow us to do this.

**Comment by cfabianski** [comment]
Another way to do it would be to run the scan again and to get the information printed after. I think it's pretty straight forward

**Comment by cfabianski** [comment]
We are currently working on making it better supported (into its own file with comments). Also the cloud will help there. 
Closing.
