### ISSUE TITLE
Add information about running bearer in airgapped environments to the official docs

### ISSUE THREAD

**Issue by 123Haynes** [Bearer/bearer#1501]
I spent today trying to get bearer to work in in airgapped environment.  
While this is possible, the documentation for it is not exactly obvious.
The docs website doesn't mention it at all and you need to switch to the bearer-rules repository to get some clues about this.

It would be nice to have a section for it in the official docs.  

The text from https://github.com/Bearer/bearer-rules?tab=readme-ov-file#how-can-i-run-my-own-version-of-these-rules-with-bearer could be used as a starting point for this.

To get bearer to run in an airgapped environment with the default rules you need to:
* clone/download the rules repository
* if you use a docker image: add the downloaded rules folder to it
* then set the correct flags for the bearer scan command.

**Comment by gotbadger** [comment]
Bearer is not really designed at the moment to be run fully airgapped. However Bearer is designed to be somewhat resliant to network connectivity issues and in some contexts as you've seen its possible to make things work. 

Since we dont really support this mode of operation we dont want to put it in the offical docs and would much prefer to do so when we had proper airgap support in the tool.
