### ISSUE TITLE
No findings when filename contains spaces

### ISSUE THREAD

**Issue by andreasbrett** [Bearer/bearer#1693]
## Description & Reproduction

When duplicating a file that produces findings and giving that file a name containing spaces, bearer will not have findings for the file.

## Expected Behavior

Findings should not be affected by the filename. 

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 1.46.1
sha: xxx
```

**Comment by elsapet** [comment]
Hi @andreasbrett - thanks for raising this. 

I am unable to reproduce the issue on my side, and it is unlikely to be related to the filename, because Bearer will scan a files regardless of spaces in their filenames.

To help me investigate further, could you share the full command you are using to run the scan? Does the issue persist even when using the `--force` flag (to rule out any caching weirdness), and/or when scanning just that single file?

**Comment by andreasbrett** [comment]
@elsapet I got this for a diff scan in a merge request in GitLab. When I tried to reproduce it without any complications added (no git, no diff), bearer indeed picked up the file with spaces.

Digging deeper I found that this is only when running bearer in diff mode (with and without --force). If the diff only contains the file with spaces, bearer will return with `couldn't find any files to scan in the specified directory, for diff scans this can mean the compared branches were identical`.

**Comment by elsapet** [comment]
Thanks @andreasbrett - the fix for your issue will be included in the next release. As it turns out, while our diff mode was handling some whitespace like tabs, it was not handling standard spaces in filenames and so in this case, the files were not being scanned. 

I'll update here when the next release is available (likely early next week).

**Comment by elsapet** [comment]
Fix is in now live at https://github.com/Bearer/bearer/releases/tag/v1.46.4

Thanks again @andreasbrett for your time in reporting the issue and the repro steps 🐻 🙏
