### ISSUE TITLE
 bufio.Scanner: token too long error when running detectors

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#718]
## Description & Reproduction

When using 

```
git clone https://github.com/Tencent/kbone
```
if we limit to one rule with --only-rule scan fails

```
bearer scan --only-rule=javascript_dangerous_insert_html ./kbone
Loading rules
Scanning target ./kbone
 └ 100% [===============] (1103/1103, 113 files/s) [9s]
Running Detectors
Error: report error: error generating report failed to decode report: bufio.Scanner: token too long
report error: error generating report failed to decode report: bufio.Scanner: token too long
 ~/development
```

strangely if you do not use the only rule filter the scan completes as expected

## Expected Behavior

scan should pass

## Actual Behavior

scan fails with error

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 0.00.0
sha: 23b10384c1300dead9e8c5a023da3bdaf8ee4131
```

**Comment by elsapet** [comment]
Also seen when running a scan with no flags set, for a particular folder.

Repro steps

1. Clone arkime 
2. Scan `arkime/viewer/public/`

Expected output

- Security report

Actual output

```
elsapet@elsapet-bearer:~/Bearer/bearer|ff9c4d92 ⇒  go run cmd/bearer/main.go scan /Users/elsapet/Bearer/battletesting/arkime/viewer/public
Loading rules
Scanning target /Users/elsapet/Bearer/battletesting/arkime/viewer/public
 └ 100% [===============] (10/10, 17 files/s) [0s]
Running Detectors
Error: report error: error generating report failed to decode report: bufio.Scanner: token too long
report error: error generating report failed to decode report: bufio.Scanner: token too long
exit status 1
```

From a manual `gitbisect`, the folder scans fine until this commit: https://github.com/Bearer/bearer/commit/f77ca4ea9f7f034e2d4efe5c52d2244503f21792

**Comment by vjerci** [comment]
Previously due to a couple of spiraled bugs one top of each other we were crashing in certain scenarios:

1. we were storing auxilary rules result in jsonlines report. (this pr addresses this problem)
2. we have a rule dangerous_insert_html which bascially had auxilary for any kind of string detection.
3. jsonlines library uses bufio.scanner, which limits token/single json line/ single detection size to 64 kb.

All that above problems coupled with a nasty webpacks compiled javascript which used eval of a string bigger than 64kb disabled us from parsing our worker report file.

pr dealing with 1. and 2. https://github.com/Bearer/bearer/pull/729
